a=int(input())
b=int(input())
c=int(input())
d=int(input())
if a<c<b: print("YES")
elif c<b<d: print("YES")
elif c<a<d: print("YES")
elif a<d<b: print("YES")
elif a==c and b==d: print("YES")
else: print("NO")